import type { Execution } from "./roi";

export const syntheticExecutions: Execution[] = [
  {
    id: "SYN-1012",
    workflowId: "voice-support-resolution-v1",
    workflowName: "Voice Support Resolution",
    outcome: "resolved",
    baselineHumanMinutes: 8.4,
    actualHumanMinutes: 0,
    automationCost: 0.42,
    automationCostCurrency: "EUR",
    qualityScore: 0.97,
    durationSeconds: 206,
    source: "synthetic",
    provider: "Vapi modelled",
    createdAt: "10:12",
    evidence: ["account.lookup", "action.invoice_copy", "resolution.confirmed"],
  },
  {
    id: "SYN-1011",
    workflowId: "voice-support-resolution-v1",
    workflowName: "Voice Support Resolution",
    outcome: "resolved",
    baselineHumanMinutes: 8.4,
    actualHumanMinutes: 0,
    automationCost: 0.38,
    automationCostCurrency: "EUR",
    qualityScore: 0.95,
    durationSeconds: 189,
    source: "synthetic",
    provider: "Vapi modelled",
    createdAt: "10:07",
    evidence: ["account.lookup", "action.password_reset", "resolution.confirmed"],
  },
  {
    id: "SYN-1010",
    workflowId: "voice-support-resolution-v1",
    workflowName: "Voice Support Resolution",
    outcome: "escalated",
    baselineHumanMinutes: 8.4,
    actualHumanMinutes: 4.1,
    automationCost: 0.29,
    automationCostCurrency: "EUR",
    qualityScore: 0.96,
    durationSeconds: 151,
    source: "synthetic",
    provider: "Vapi modelled",
    createdAt: "10:02",
    evidence: ["account.lookup", "policy.high_impact", "handoff.created"],
  },
  {
    id: "SYN-1009",
    workflowId: "voice-support-resolution-v1",
    workflowName: "Voice Support Resolution",
    outcome: "resolved",
    baselineHumanMinutes: 8.4,
    actualHumanMinutes: 0,
    automationCost: 0.31,
    automationCostCurrency: "EUR",
    qualityScore: 0.93,
    durationSeconds: 164,
    source: "synthetic",
    provider: "Vapi modelled",
    createdAt: "09:58",
    evidence: ["account.lookup", "action.service_status", "resolution.confirmed"],
  },
  {
    id: "SYN-1008",
    workflowId: "voice-support-resolution-v1",
    workflowName: "Voice Support Resolution",
    outcome: "resolved",
    baselineHumanMinutes: 8.4,
    actualHumanMinutes: 0,
    automationCost: 0.47,
    automationCostCurrency: "EUR",
    qualityScore: 0.92,
    durationSeconds: 230,
    source: "synthetic",
    provider: "Vapi modelled",
    createdAt: "09:51",
    evidence: ["clarification", "account.lookup", "action.invoice_copy"],
  },
  {
    id: "SYN-1007",
    workflowId: "voice-support-resolution-v1",
    workflowName: "Voice Support Resolution",
    outcome: "escalated",
    baselineHumanMinutes: 8.4,
    actualHumanMinutes: 3.8,
    automationCost: 0.24,
    automationCostCurrency: "EUR",
    qualityScore: 0.95,
    durationSeconds: 126,
    source: "synthetic",
    provider: "Vapi modelled",
    createdAt: "09:45",
    evidence: ["human_requested", "handoff.created"],
  },
  {
    id: "SYN-1006",
    workflowId: "voice-support-resolution-v1",
    workflowName: "Voice Support Resolution",
    outcome: "failed",
    baselineHumanMinutes: 8.4,
    actualHumanMinutes: 8.4,
    automationCost: 0.21,
    automationCostCurrency: "EUR",
    qualityScore: 0.61,
    durationSeconds: 111,
    source: "synthetic",
    provider: "Vapi modelled",
    createdAt: "09:41",
    evidence: ["tool.timeout", "retry.exhausted", "call.ended"],
  },
  {
    id: "SYN-1005",
    workflowId: "voice-support-resolution-v1",
    workflowName: "Voice Support Resolution",
    outcome: "resolved",
    baselineHumanMinutes: 8.4,
    actualHumanMinutes: 0,
    automationCost: 0.35,
    automationCostCurrency: "EUR",
    qualityScore: 0.94,
    durationSeconds: 177,
    source: "synthetic",
    provider: "Vapi modelled",
    createdAt: "09:35",
    evidence: ["account.lookup", "action.password_reset", "resolution.confirmed"],
  },
  {
    id: "SYN-1004",
    workflowId: "voice-support-resolution-v1",
    workflowName: "Voice Support Resolution",
    outcome: "resolved",
    baselineHumanMinutes: 8.4,
    actualHumanMinutes: 0,
    automationCost: 0.33,
    automationCostCurrency: "EUR",
    qualityScore: 0.91,
    durationSeconds: 170,
    source: "synthetic",
    provider: "Vapi modelled",
    createdAt: "09:29",
    evidence: ["account.lookup", "action.invoice_copy", "resolution.confirmed"],
  },
  {
    id: "SYN-1003",
    workflowId: "voice-support-resolution-v1",
    workflowName: "Voice Support Resolution",
    outcome: "resolved",
    baselineHumanMinutes: 8.4,
    actualHumanMinutes: 0,
    automationCost: 0.36,
    automationCostCurrency: "EUR",
    qualityScore: 0.96,
    durationSeconds: 181,
    source: "synthetic",
    provider: "Vapi modelled",
    createdAt: "09:23",
    evidence: ["account.lookup", "action.service_status", "resolution.confirmed"],
  },
  {
    id: "SYN-1002",
    workflowId: "voice-support-resolution-v1",
    workflowName: "Voice Support Resolution",
    outcome: "escalated",
    baselineHumanMinutes: 8.4,
    actualHumanMinutes: 4.5,
    automationCost: 0.27,
    automationCostCurrency: "EUR",
    qualityScore: 0.9,
    durationSeconds: 142,
    source: "synthetic",
    provider: "Vapi modelled",
    createdAt: "09:18",
    evidence: ["account.not_found", "handoff.created"],
  },
  {
    id: "SYN-1001",
    workflowId: "voice-support-resolution-v1",
    workflowName: "Voice Support Resolution",
    outcome: "resolved",
    baselineHumanMinutes: 8.4,
    actualHumanMinutes: 0,
    automationCost: 0.4,
    automationCostCurrency: "EUR",
    qualityScore: 0.93,
    durationSeconds: 198,
    source: "synthetic",
    provider: "Vapi modelled",
    createdAt: "09:11",
    evidence: ["account.lookup", "action.invoice_copy", "resolution.confirmed"],
  },
];

export const readinessChecks = [
  { label: "Business baseline captured", value: 100, gate: true },
  { label: "Tool contracts deterministic", value: 100, gate: true },
  { label: "Critical safety evals passing", value: 100, gate: true },
  { label: "Synthetic reliability suite", value: 96, gate: true },
  { label: "Human handoff tested", value: 100, gate: true },
  { label: "Provider cost evidence", value: 70, gate: false },
  { label: "Production data persistence", value: 35, gate: false },
];

export function makeSimulatedExecution(index: number): Execution {
  const template = syntheticExecutions[index % syntheticExecutions.length];
  const now = new Date();
  return {
    ...template,
    id: `SIM-${now.getTime().toString().slice(-6)}`,
    source: "estimated",
    provider: "LaunchForge simulator",
    createdAt: now.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
  };
}
